function CFA_template(H)
% function CFA_template
movegui(H.fig,'west');

load('SetUpPara.mat');

pathss = which('CFA_template.m');
[pth nam ext] = fileparts(pathss);
ParaSavedir = [pth,filesep,'IOparameter',filesep];
Htemp.ParaSavedir = ParaSavedir;

Htemp.fig = figure('unit','norm',...
    'pos',[0.2,0.2,0.6,0.6],...
    'menubar','none',...
    'color','w',...
    'name','Template & heatmapparameer setup');
Htemp.tempbg = uibuttongroup('parent',Htemp.fig,...
    'unit','norm',...
    'pos',[0.1,0.5,0.8,0.4],...
    'title','Atlas Selection');
%
Htemp.tempsel1 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[0,5/6,1/4,1/6],...
    'style','checkbox',...
    'string','FiveTissue',...
    'val',1);
Htemp.tempsel2 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[0,4/6,1/4,1/6],...
    'style','checkbox',...
    'string','FiveTissue LR',...
    'val',1);
Htemp.tempsel3 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[1/4,2/3,1/4,1/3],...
    'style','checkbox',...
    'string','JHU (Gray+White)',...
    'val',1);
Htemp.tempsel4 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[2/4,2/3,1/4,1/3],...
    'style','checkbox',...
    'string','LPBA40',...
    'val',1);
%
Htemp.tempsel5 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[3/4,2/3,1/4,1/3],...
    'style','checkbox',...
    'string','AAL',...
    'val',1);
Htemp.tempsel6 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[0,1/3,1/4,1/3],...
    'style','checkbox',...
    'string','HOA cortex',...
    'val',1);
Htemp.tempsel7 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[1/4,1/3,1/4,1/3],...
    'style','checkbox',...
    'string','HOA subcortex',...
    'val',1);
Htemp.tempsel8 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[2/4,1/3,1/4,1/3],...
    'style','checkbox',...
    'string','Mesulam HOA',...
    'val',1);
%
Htemp.tempsel9 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[3/4,1/3,1/4,1/3],...
    'style','checkbox',...
    'string','JHU whitematter',...
    'val',1);
Htemp.tempsel10 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[0,0,1/4,1/3],...
    'style','checkbox',...
    'string','ICBM whitematter',...
    'val',1);
Htemp.tempsel11 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[1/4,0,1/4,1/3],...
    'style','checkbox',...
    'string','Ventricle',...
    'val',1);
Htemp.tempsel12 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[2/4,0,1/4,1/3],...
    'style','checkbox',...
    'string','Arterial',...
    'val',1);
%%

Htemp.tempsel13 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[3/4,2/9,1/4,1/9],...
    'style','checkbox',...
    'string','Other',...
    'val',0);
Htemp.tempsel13_1 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[3/4,1/9,1/4,1/9],...
    'style','edit',...
    'string','Template dir',...
    'enable','off');
Htemp.tempsel13_2 = uicontrol('parent',Htemp.tempbg,...
    'unit','norm',...
    'pos',[3/4,0/9,1/4,1/9],...
    'style','edit',...
    'string','ROIname dir',...
    'enable','off');

%%
%%
% Htemp.VLSMsetup = uibuttongroup('parent',Htemp.fig,...
%     'unit','norm',...
%     'pos',[0.1,0.4,0.8,0.1],...
%     'title','VLSM setup');
% Htemp.IgnorePercent = uicontrol('parent',Htemp.VLSMsetup,...
%     'unit','norm',...
%     'pos',[0.05,0.1,0.1,0.8],...
%     'string',{'Ignore voxel', 'less than (%)'},...
%     'style','text');
% Htemp.IgnorePercentE = uicontrol('parent',Htemp.VLSMsetup,...
%     'unit','norm',...
%     'pos',[0.15,0.3,0.03,0.4],...
%     'style','edit',...
%     'string','10');
% Htemp.VLSMcal = uicontrol('parent',Htemp.VLSMsetup,...
%     'unit','norm',...
%     'pos',[0.25,0.1,0.2,0.8],...
%     'style','checkbox',...
%     'string','VLSM analysis',...
%     'val',1);
% 
% conlab = 0;
% for i = 1:length(SetUpPara.ParaOut)
%     Varlab = SetUpPara.ParaOut(i).dattype;
%     if Varlab==0
%         conlab = 1;
%         break;
%     end    
% end
% Htemp.VLSMVarCon = uicontrol('parent',Htemp.VLSMsetup,...
%     'unit','norm',...
%     'pos',[0.45,0.6,0.25,0.3],...
%     'style','checkbox',...
%     'string','use Continous Variables',...
%     'val',0,...
%     'enable','off');
% if conlab==1
%     set(Htemp.VLSMVarCon,'enable','on');
% end
% Htemp.VLSMVarnew = uicontrol('parent',Htemp.VLSMsetup,...
%     'unit','norm',...
%     'pos',[0.45,0.1,0.25,0.3],...
%     'style','checkbox',...
%     'string','New Clincal Variables',...
%     'val',1);
% Htemp.VLSMcov = uicontrol('parent',Htemp.VLSMsetup,...
%     'unit','norm',...
%     'pos',[0.7,0.1,0.25,0.8],...
%     'style','checkbox',...
%     'string','Covariable of No Interest',...
%     'val',0);

Htemp.IgnorePercent = uicontrol('parent',Htemp.fig,...
    'unit','norm',...
    'pos',[0.1,0.41,0.08,0.08],...
    'string',{'Ignore voxel', 'less than (%)'},...
    'style','text');
Htemp.IgnorePercentE = uicontrol('parent',Htemp.fig,...
    'unit','norm',...
    'pos',[0.18,0.43,0.02,0.04],...
    'style','edit',...
    'string','1');
Htemp.VLSMsetup = uibuttongroup('parent',Htemp.fig,...
    'unit','norm',...
    'pos',[0.2,0.4,0.7,0.1],...
    'title','VLSM setup');

Htemp.VLSMcal = uicontrol('parent',Htemp.VLSMsetup,...
    'unit','norm',...
    'pos',[0.15,0.1,0.2,0.8],...
    'style','checkbox',...
    'string','VLSM analysis',...
    'val',1);
conlab = 0;
for i = 1:length(SetUpPara.ParaOut)
    Varlab = SetUpPara.ParaOut(i).dattype;
    if Varlab==0
        conlab = 1;
        break;
    end    
end
Htemp.VLSMVarCon = uicontrol('parent',Htemp.VLSMsetup,...
    'unit','norm',...
    'pos',[0.35,0.6,0.25,0.3],...
    'style','checkbox',...
    'string','use Continous Variables',...
    'val',0,...
    'enable','off');
if conlab==1
    set(Htemp.VLSMVarCon,'enable','on');
end
Htemp.VLSMVarnew = uicontrol('parent',Htemp.VLSMsetup,...
    'unit','norm',...
    'pos',[0.35,0.1,0.25,0.3],...
    'style','checkbox',...
    'string','New Clincal Variables',...
    'val',1);
Htemp.VLSMcov = uicontrol('parent',Htemp.VLSMsetup,...
    'unit','norm',...
    'pos',[0.6,0.1,0.25,0.8],...
    'style','checkbox',...
    'string','Covariable of No Interest',...
    'val',0);

%%
%%
Htemp.heatbg = uibuttongroup('parent',Htemp.fig,...
    'unit','norm',...
    'pos',[0.1,0.1,0.6,0.3],...
    'title','Heatmap Parameter');
%% heatnumber
Htemp.heatpara_HeatnumMod = uibuttongroup('parent',Htemp.heatbg,...
    'unit','norm',...
    'pos',[0,0,1/5,1],...
    'title','Heat Number');
%
Htemp.heatpara_heatnumSelV = uicontrol('parent',Htemp.heatpara_HeatnumMod,...
    'unit','norm',...
    'pos',[0,3/4,1,1/4],...
    'style','checkbox',...
    'string','VoxelWise',...
    'val',1);

Htemp.heatpara_heatnumSelROI = uicontrol('parent',Htemp.heatpara_HeatnumMod,...
    'unit','norm',...
    'pos',[0,2/4,0.7,1/4],...
    'style','checkbox',...
    'string','ROIwise >',...
    'val',1);
Htemp.heatpara_heatnumSelROIedit = uicontrol('parent',Htemp.heatpara_HeatnumMod,...
    'unit','norm',...
    'pos',[0.7,2/4,0.2,1/4],...
    'style','edit',...
    'string','0');
Htemp.heatpara_heatnumSelROIt = uicontrol('parent',Htemp.heatpara_HeatnumMod,...
    'unit','norm',...
    'pos',[0.9,2/4,0.1,1/4],...
    'style','text',...
    'string','%');
Htemp.heatpara_heatnumStatC = uicontrol('parent',Htemp.heatpara_HeatnumMod,...
    'unit','norm',...
    'pos',[0,1/4,1,1/4],...
    'style','checkbox',...
    'string','Chi-square',...
    'val',1);
Htemp.heatpara_heatnumStatP = uicontrol('parent',Htemp.heatpara_HeatnumMod,...
    'unit','norm',...
    'pos',[0,0/4,1,1/4],...
    'style','checkbox',...
    'string','permutation',...
    'val',1);
%% cent number
Htemp.heatpara_CentMod = uibuttongroup('parent',Htemp.heatbg,...
    'unit','norm',...
    'pos',[1/5,0,1/5,1],...
    'title','Center Number');
%
% Htemp.heatpara_CentSelV = uicontrol('parent',Htemp.heatpara_CentMod,...
%     'unit','norm',...
%     'pos',[0,3/4,1,1/4],...
%     'style','checkbox',...
%     'string','VoxelWise',...
%     'val',1);

Htemp.heatpara_CentSelROI = uicontrol('parent',Htemp.heatpara_CentMod,...
    'unit','norm',...
    'pos',[0,2/4,0.7,1/4],...
    'style','checkbox',...
    'string','ROIwise',...
    'val',1);
% Htemp.heatpara_CentSelROIedit = uicontrol('parent',Htemp.heatpara_CentMod,...
%     'unit','norm',...
%     'pos',[0.7,2/4,0.2,1/4],...
%     'style','edit',...
%     'string','0',...
%     'val',1);
% Htemp.heatpara_CentSelROIt = uicontrol('parent',Htemp.heatpara_CentMod,...
%     'unit','norm',...
%     'pos',[0.9,2/4,0.1,1/4],...
%     'style','text',...
%     'string','%',...
%     'val',1);
Htemp.heatpara_CentStatC = uicontrol('parent',Htemp.heatpara_CentMod,...
    'unit','norm',...
    'pos',[0,1/4,1,1/4],...
    'style','checkbox',...
    'string','Chi-square',...
    'val',1);
Htemp.heatpara_CentStatP = uicontrol('parent',Htemp.heatpara_CentMod,...
    'unit','norm',...
    'pos',[0,0/4,1,1/4],...
    'style','checkbox',...
    'string','permutation',...
    'val',1);
%% affected volume
Htemp.heatpara_AffVolMod = uibuttongroup('parent',Htemp.heatbg,...
    'unit','norm',...
    'pos',[2/5,3/5,1/5,2/5],...
    'title','Affected Volume');
%
% Htemp.heatpara_AffVolSelV = uicontrol('parent',Htemp.heatpara_AffVolMod,...
%     'unit','norm',...
%     'pos',[0,3/4,1,1/4],...
%     'style','checkbox',...
%     'string','VoxelWise',...
%     'val',1);

Htemp.heatpara_AffVolSelROI = uicontrol('parent',Htemp.heatpara_AffVolMod,...
    'unit','norm',...
    'pos',[0,0.5,0.7,0.5],...
    'style','checkbox',...
    'string','ROIwise',...
    'val',1);
% Htemp.heatpara_AffVolSelROIedit = uicontrol('parent',Htemp.heatpara_AffVolMod,...
%     'unit','norm',...
%     'pos',[0.7,2/4,0.2,1/4],...
%     'style','edit',...
%     'string','0',...
%     'val',1);
% Htemp.heatpara_AffVolSelROIt = uicontrol('parent',Htemp.heatpara_AffVolMod,...
%     'unit','norm',...
%     'pos',[0.9,2/4,0.1,1/4],...
%     'style','text',...
%     'string','%',...
%     'val',1);
% Htemp.heatpara_AffVolStatC = uicontrol('parent',Htemp.heatpara_AffVolMod,...
%     'unit','norm',...
%     'pos',[0,1/4,1,1/4],...
%     'style','checkbox',...
%     'string','Chi-square',...
%     'val',1);
Htemp.heatpara_AffVolStatP = uicontrol('parent',Htemp.heatpara_AffVolMod,...
    'unit','norm',...
    'pos',[0,0,1,0.5],...
    'style','checkbox',...
    'string','permutation',...
    'val',1);

%% Clinc Weighted Location
Htemp.heatpara_WeiLocMod = uibuttongroup('parent',Htemp.heatbg,...
    'unit','norm',...
    'pos',[2/5,0,1/5,3/5],...
    'title','Weighted Location');

Htemp.heatpara_VolWeiLoc = uicontrol('parent',Htemp.heatpara_WeiLocMod,...
    'unit','norm',...
    'pos',[0,2/3,0.7,1/3],...
    'style','checkbox',...
    'string','Volume',...
    'val',1);
Htemp.heatpara_ClincWeiLoc = uicontrol('parent',Htemp.heatpara_WeiLocMod,...
    'unit','norm',...
    'pos',[0,1/3,1,1/3],...
    'style','checkbox',...
    'string','Clinc Var',...
    'val',1);
Htemp.heatpara_WeiLocStatP = uicontrol('parent',Htemp.heatpara_WeiLocMod,...
    'unit','norm',...
    'pos',[0,0,1,1/3],...
    'style','checkbox',...
    'string','permutation',...
    'val',1);

%%
Htemp.heatpara_WeightedCentMod = uibuttongroup('parent',Htemp.heatbg,...
    'unit','norm',...
    'pos',[3/5,0,1/5,1],...
    'title','Volume weighted Center');
%
Htemp.heatpara_WeightedCentSelV = uicontrol('parent',Htemp.heatpara_WeightedCentMod,...
    'unit','norm',...
    'pos',[0,3/4,1,1/4],...
    'style','checkbox',...
    'string','VoxelWise',...
    'val',1);

%%
Htemp.heatpara_WeightedCentSelROI = uicontrol('parent',Htemp.heatpara_WeightedCentMod,...
    'unit','norm',...
    'pos',[0,2/4,0.7,1/4],...
    'style','checkbox',...
    'string','ROIwise',...
    'val',1);
%%
% Htemp.heatpara_WeightedCentSelROI = uicontrol('parent',Htemp.heatpara_WeightedCentMod,...
%     'unit','norm',...
%     'pos',[0,2/4,0.7,1/4],...
%     'style','checkbox',...
%     'string','ROIwise >',...
%     'val',1);
% Htemp.heatpara_WeightedCentSelROIedit = uicontrol('parent',Htemp.heatpara_WeightedCentMod,...
%     'unit','norm',...
%     'pos',[0.7,2/4,0.2,1/4],...
%     'style','edit',...
%     'string','0',...
%     'val',1);
% Htemp.heatpara_WeightedCentSelROIt = uicontrol('parent',Htemp.heatpara_WeightedCentMod,...
%     'unit','norm',...
%     'pos',[0.9,2/4,0.1,1/4],...
%     'style','text',...
%     'string','%',...
%     'val',1);
%%

% Htemp.heatpara_WeightedCentStatC = uicontrol('parent',Htemp.heatpara_WeightedCentMod,...
%     'unit','norm',...
%     'pos',[0,1/4,1,1/4],...
%     'style','checkbox',...
%     'string','Chi-square',...
%     'val',1);
Htemp.heatpara_WeightedCentStatP = uicontrol('parent',Htemp.heatpara_WeightedCentMod,...
    'unit','norm',...
    'pos',[0,0/4,1,1/4],...
    'style','checkbox',...
    'string','permutation',...
    'val',1);
%%
Htemp.heatpara_Otherpara = uibuttongroup('parent',Htemp.heatbg,...
    'unit','norm',...
    'pos',[4/5,0,1/5,1],...
    'title','Other parameter');
% Htemp.heatpara_Otherparapb = uicontrol('parent',Htemp.heatpara_Otherpara,...
%     'unit','norm',...
%     'pos',[0,0,1,1],...
%     'style','text',...
%     'string','comming soon!');
Htemp.heatpara_histgrampara = uicontrol('parent',Htemp.heatpara_Otherpara,...
    'unit','norm',...
    'pos',[0,1/2,1,1/2],...
    'style','checkbox',...
    'string','Histgram Parameter',...
    'val',1);
Htemp.heatpara_dis2Ventricle = uicontrol('parent',Htemp.heatpara_Otherpara,...
    'unit','norm',...
    'pos',[0,0,1,1/2],...
    'style','checkbox',...
    'string','distance to Ventricle',...
    'val',1);
%%
Htemp.OK = uicontrol('parent',Htemp.fig,...
    'unit','norm',...
    'pos',[0.75,0.1,0.15,0.1],...
    'style','pushbutton',...
    'string','Finish!');

set(Htemp.VLSMcal,'callback',{@VLSMinfosetup,Htemp,conlab});
set(Htemp.tempsel13,'callback',{@SelOtherTemp,Htemp});
set(Htemp.OK,'callback',{@OKbutton,Htemp,H});
% set(Htemp.OK,'callback',{@OKbutton2,Htemp});
end
function VLSMinfosetup(varargin)
Htemp = varargin{3};
conlab = varargin{4};
VALs = get(Htemp.VLSMcal,'val');
if VALs==1
    if conlab==1
        set(Htemp.VLSMVarCon,'enable','on');
    else
        set(Htemp.VLSMVarCon,'enable','off');
    end
    set(Htemp.VLSMVarnew,'enable','on');
    set(Htemp.VLSMcov,'enable','on');
else
    set(Htemp.VLSMVarCon,'enable','off');
    set(Htemp.VLSMVarnew,'enable','off');
    set(Htemp.VLSMcov,'enable','off');  
end

end
function SelOtherTemp(varargin)
Htemp = varargin{3};
VALs = get(Htemp.tempsel13,'val');
if VALs==1
    [file,pth] = uigetfile({'*.nii';'*.nii.gz';'*.hdr';'*.img'},'Select ROI template');
    PGs = fullfile(pth,file);
    set(Htemp.tempsel13_1,'enable','on');
    set(Htemp.tempsel13_1,'string',PGs);
    uiwait(msgbox('Make sure: 1. Variable name: ROItabb; 2. the first column was ROI index, the second column was ROI name!'))
    [file2,pth2] = uigetfile('*.mat','Select ROI namelist, varname; ROItab');
    PGs2 = fullfile(pth2,file2);
    set(Htemp.tempsel13_2,'enable','on');
    set(Htemp.tempsel13_2,'string',PGs2);
else    
    set(Htemp.tempsel13_1,'enable','off');
    set(Htemp.tempsel13_2,'enable','off');
    set(Htemp.tempsel13_1,'string','');
    set(Htemp.tempsel13_2,'string','');    
end
end
function OKbutton(varargin)
Htemp = varargin{3};
H = varargin{4};
Template.Fivetissue = get(Htemp.tempsel1,'val');
Template.FivetissueLR = get(Htemp.tempsel2,'val');
Template.JHUtotal = get(Htemp.tempsel3,'val');
Template.LPBA40 = get(Htemp.tempsel4,'val');
Template.AAL = get(Htemp.tempsel5,'val');
Template.HOAcortex = get(Htemp.tempsel6,'val');
Template.HOAsubcortex = get(Htemp.tempsel7,'val');
Template.MesulamHOA = get(Htemp.tempsel8,'val');
Template.JHUwhite = get(Htemp.tempsel9,'val');
Template.ICBMwhite = get(Htemp.tempsel10,'val');
Template.Ventricle = get(Htemp.tempsel11,'val');
Template.Arterial = get(Htemp.tempsel12,'val');
Template.Other = get(Htemp.tempsel13,'val');
Template.OtherROI = get(Htemp.tempsel13_1,'string');
Template.OtherROIname = get(Htemp.tempsel13_2,'string');
%%
Para.Heat.V = get(Htemp.heatpara_heatnumSelV,'val');
Para.Heat.R = get(Htemp.heatpara_heatnumSelROI,'val');
Para.Heat.Rper = str2num(get(Htemp.heatpara_heatnumSelROIedit,'string'));
Para.Heat.StChisquare = get(Htemp.heatpara_heatnumStatC,'val');
Para.Heat.StPermutation = get(Htemp.heatpara_heatnumStatP,'val');

Para.CentNum.R = get(Htemp.heatpara_CentSelROI,'val');
Para.CentNum.StChisquare = get(Htemp.heatpara_CentStatC,'val');
Para.CentNum.StPermutation = get(Htemp.heatpara_CentStatP,'val');

Para.AffVolume.R = get(Htemp.heatpara_AffVolSelROI,'val');
Para.AffVolume.StPermutation = get(Htemp.heatpara_AffVolStatP,'val');

Para.WeiCent.R = get(Htemp.heatpara_WeightedCentSelV,'val');
Para.WeiCent.StPermutation = get(Htemp.heatpara_AffVolStatP,'val');

Para.WeiCent.V = get(Htemp.heatpara_WeightedCentSelV,'val');
Para.WeiCent.R = get(Htemp.heatpara_WeightedCentSelROI,'val');
% Para.WeiCent.Rper = get(Htemp.heatpara_WeightedCentSelROIedit,'string');
Para.WeiCent.StPermutation = get(Htemp.heatpara_WeightedCentStatP,'val');
Para.Other.Hist = get(Htemp.heatpara_histgrampara,'val');
Para.Other.D2V = get(Htemp.heatpara_dis2Ventricle,'val');

Para.WeiLoc.Vol = get(Htemp.heatpara_VolWeiLoc,'val');
Para.WeiLoc.Clin = get(Htemp.heatpara_ClincWeiLoc,'val');
Para.WeiLoc.StPermutation = get(Htemp.heatpara_WeiLocStatP,'val');

Para.IgP = str2num(get(Htemp.IgnorePercentE,'string'));
Para.VLSM.ana = get(Htemp.VLSMcal,'val');
Para.VLSM.VarCon = get(Htemp.VLSMVarCon,'val');
Para.VLSM.VarNew = get(Htemp.VLSMVarnew,'val');
Para.VLSM.COV = get(Htemp.VLSMcov,'val');
% Para.Other = get(Htemp.heatpara_Otherparapb,'string')
%%
save('Setup_TempAndPara.mat','Para','Template');
close(Htemp.fig);
movegui(H.fig,'center')
end
