function CFA_ReGroupData
uiwait(msgbox({'This is a simple function for Re-Group Data!',...
    'Suitable conditions:',...
    '1. Each subfold contains 1 ROI and 1 EPI/T1/T2/CT file',...
    '2. Each subfold contains 1 ROI 1 T1 file and 1 other file',...
    '3. One Fold contains ROI files, and one fold contains EPI/T1/T2/CT files',...
    '4. One Fold contains ROI files, one fold contains T1 file, and one fold contains other files'}));
%     '4. One Fold contains ROI files, one fold contains T1 file, and one fold contains other files',...
%     '5. One Fold contains ROI files, one fold containes T1 files and other files'}));

filpth = which('CFA_ReGroupData.m');
[pth fil ext] = fileparts(filpth);
matdir = [pth,filesep,'ReGroup',filesep];
if isempty(dir(matdir))
    mkdir(matdir);
else
    rmdir(matdir,'s')
    mkdir(matdir);
end
ReGD.fig = figure('unit','norm',...
    'pos',[0.3,0.4,0.4,0.2],...
    'menubar','none',...
    'color','w',...
    'name','Re-Group Data for Clinical Freqency Analysis');
ReGD.DataType = uibuttongroup('parent',ReGD.fig,...
    'unit','norm',...
    'pos',[0.1,0.55,0.8,0.4],...
    'title','Dat Condition');

ReGD.type1 = uicontrol('parent',ReGD.DataType,...
    'unit','norm',...
    'pos',[0,0,1/5,1],...
    'style','rad',...
    'string','EPI mode');
ReGD.type2 = uicontrol('parent',ReGD.DataType,...
    'unit','norm',...
    'pos',[1/5,0,1/5,1],...
    'style','rad',...
    'string','T1 mode');
ReGD.type3 = uicontrol('parent',ReGD.DataType,...
    'unit','norm',...
    'pos',[2/5,0,1/5,1],...
    'style','rad',...
    'string','withT1 mode');
ReGD.type4 = uicontrol('parent',ReGD.DataType,...
    'unit','norm',...
    'pos',[3/5,0,1/5,1],...
    'style','rad',...
    'string','T2 mode');
ReGD.type5 = uicontrol('parent',ReGD.DataType,...
    'unit','norm',...
    'pos',[4/5,0,1/5,1],...
    'style','rad',...
    'string','CT mode');

ReGD.DatFold = uibuttongroup('parent',ReGD.fig,...
    'unit','norm',...
    'pos',[0.1,0.05,0.6,0.4],...
    'title','Dat Fold condition');
ReGD.DatType1 = uicontrol('parent',ReGD.DatFold,...
    'unit','norm',...
    'pos',[0,0,0.5,1],...
    'style','rad',...
    'string','All in one fold');

ReGD.DatType2 = uicontrol('parent',ReGD.DatFold,...
    'unit','norm',...
    'pos',[0.5,0,0.5,1],...
    'style','rad',...
    'string','Seperated ROI&BackFiles');

ReGD.DoJob = uicontrol('parent',ReGD.fig,...
    'unit','norm',...
    'pos',[0.75,0.05,0.15,0.4],...
    'style','pushbutton',...
    'string','Do The Job');
set(ReGD.DoJob,'callback',{@ReGDDoJob,ReGD,matdir});
end
function ReGDDoJob(varargin)
ReGD = varargin{3};
matdir = varargin{4};
DatCond1 = get(ReGD.type1,'val');
DatCond2 = get(ReGD.type2,'val');
DatCond3 = get(ReGD.type3,'val');
DatCond4 = get(ReGD.type4,'val');
DatCond5 = get(ReGD.type5,'val');

DatFoldcond1 = get(ReGD.DatType1,'val');
DatFoldcond2 = get(ReGD.DatType2,'val');
if DatCond1
    Para.DatC = 1;
elseif DatCond2
    Para.DatC = 2;
elseif DatCond3
    Para.DatC = 3;
elseif DatCond4
    Para.DatC = 4;
elseif DatCond5
    Para.DatC = 5;
end
if DatFoldcond1
    Para.DatF = 1;
elseif DatFoldcond2
    Para.DatF = 2;
end

if Para.DatF==1    % All in fold
    PG = uigetdir(pwd,'Indir');
    subindexs = dir(PG);
    %%
    totalnum = length(subindexs)-2;
    NUMSEP = 25;
    sepno = floor(totalnum/NUMSEP);
    for i = 1:sepno
        Seps{i,1} = 1+NUMSEP*(i-1):NUMSEP*i;
    end
    if totalnum>sepno*NUMSEP
        sepno = sepno+1;
        Seps{sepno,1} = NUMSEP*(sepno-1)+1:totalnum;
    end
    %%
    if subindexs(3).isdir
        Subtype = 1;
        for i = 1:length(subindexs)-2
            dirtemp{i,1} = [PG,filesep,subindexs(i+2).name,filesep];
            namelist{i,1} = subindexs(i+2).name;
        end
    else
        Subtype = 2;
        for i = 1:length(subindexs)-2
            files{i,1} = [PG,filesep,subindexs(i+2).name];            
            namelist{i,1} = subindexs(i+2).name;
        end
    end
    cond1 = 0;
    switch Para.DatC
        case 1 % EPI
            Lab = 'EPI';
        case 2 % t1            
            Lab = 'T1';
        case 3 % with T1
            cond1 = 1;
            Lab = 'withT1';
        case 4 % T2            
            Lab = 'T2';
        case 5 % CT            
            Lab = 'CT';
        otherwise
            
    end    
    if Subtype==1
        for i = 1:sepno
            numtemp = 1;
            for j = Seps{i}
                subfil1 = dir([dirtemp{j},filesep,'*.nii']);
                subfil2 = dir([dirtemp{j},filesep,'*.hdr']);
                subfil3 = dir([dirtemp{j},filesep,'*.nii.gz']);
                dirs{numtemp,1} = dirtemp{j};
                numfiltemp = 1;
                for k = 1:length(subfil1)
                    Tempfile{numtemp,numfiltemp} = subfil1(k).name;
                    numfiltemp = numfiltemp+1;
                end
                for k = 1:length(subfil2)
                    Tempfile{numtemp,numfiltemp} = subfil2(k).name;
                    numfiltemp = numfiltemp+1;
                end
                for k = 1:length(subfil3)
                    Tempfile{numtemp,numfiltemp} = subfil3(k).name;
                    numfiltemp = numfiltemp+1;
                end
                numtemp = numtemp+1;
            end
            
            if cond1==0
                if i~=sepno
                    SelEPIT1T2CT(Tempfile,i,'next',matdir,0,Lab,dirs,namelist);
                else
                    SelEPIT1T2CT(Tempfile,i,'done',matdir,1,Lab,dirs,namelist);
                end
                clear Tempfile
            else
                if i~=sepno
                    SelWithT1(Tempfile,i,'next',matdir,0,Lab,dirs,namelist);
                else
                    SelWithT1(Tempfile,i,'done',matdir,1,Lab,dirs,namelist);
                end
                clear Tempfile
            end
        end
    else % Subtype==2
        if cond1==0
            totalnum = length(namelist);
            DAT1 = namelist(1:totalnum/2);
            DAT2 = namelist(totalnum/2+1:totalnum);
            DAT3 = namelist(1:2:totalnum);
            DAT4 = namelist(2:2:totalnum);
            SeltypeCond1(totalnum,DAT1,DAT2,DAT3,DAT4,files)
%             files
%             namelist
        else % with T1 mode            
            totalnum = length(namelist);
            DAT1 = namelist(1:totalnum/3);
            DAT2 = namelist(totalnum/3+1:totalnum/3*2);
            DAT3 = namelist(totalnum/3*2+1:totalnum);
            DAT4 = namelist(1:3:totalnum);
            DAT5 = namelist(2:3:totalnum);
            DAT6 = namelist(3:3:totalnum);
            SeltypeCond2(totalnum,DAT1,DAT2,DAT3,DAT4,DAT5,DAT6,files)
        end
    end
else     % ROI and Data in different Fold
    cond1 = 0;
    switch Para.DatC
        case 1 % EPI
            Lab = 'EPI';
        case 2 % t1            
            Lab = 'T1';
        case 3 % with T1
            cond1 = 1;
            Lab = 'withT1';
        case 4 % T2            
            Lab = 'T2';
        case 5 % CT            
            Lab = 'CT';
        otherwise
            
    end  
    if cond1==0
        PG1 = uigetdir(pwd,'Select ROI folder');
        PG2 = uigetdir(pwd,['Select ',Lab,' folder']);
        PGout = uigetdir(pwd,'Outdirs');
        files1 = dir([PG1,filesep,'*.nii']);
        if isempty(files1)
            files1 = dir([PG1,filesep,'*.hdr']);
        end
        if isempty(files1)
            files1 = dir([PG1,filesep,'*.nii.gz']);
        end
        for i = 1:length(files1)
            ROIdirs{i,1} = [PG1,filesep,files1(i).name];
        end
        
        files2 = dir([PG2,filesep,'*.nii']);
        if isempty(files2)
            files2 = dir([PG2,filesep,'*.hdr']);
        end
        if isempty(files2)
            files1 = dir([PG2,filesep,'*.nii.gz']);
        end
        for i = 1:length(files2)
            IMGdirs{i,1} = [PG2,filesep,files2(i).name];
            NAMETEMP = files2(i).name;
            dotind = find(NAMETEMP=='.');
            namelist{i,1} = NAMETEMP(1:dotind(1)-1);
        end
        
        copydata2target(PGout,ROIdirs,IMGdirs,namelist)
    else
        PG1 = uigetdir(pwd,'Select ROI folder');
        PG2 = uigetdir(pwd,'Select T1 folder');
        PG3 = uigetdir(pwd,'Select Other folder');
        PGout = uigetdir(pwd,'Outdirs');   
        files1 = dir([PG1,filesep,'*.nii']);
        if isempty(files1)
            files1 = dir([PG1,filesep,'*.hdr']);
        end
        if isempty(files1)
            files1 = dir([PG1,filesep,'*.nii.gz']);
        end
        for i = 1:length(files1)
            ROIdirs{i,1} = [PG1,filesep,files1(i).name];
        end
        
        files2 = dir([PG2,filesep,'*.nii']);
        if isempty(files2)
            files2 = dir([PG2,filesep,'*.hdr']);
        end
        if isempty(files2)
            files1 = dir([PG2,filesep,'*.nii.gz']);
        end
        for i = 1:length(files2)
            T1dirs{i,1} = [PG2,filesep,files2(i).name];
            NAMETEMP = files2(i).name;
            dotind = find(NAMETEMP=='.');
            namelist{i,1} = NAMETEMP(1:dotind(1)-1);
        end
        
        files3 = dir([PG3,filesep,'*.nii']);
        if isempty(files3)
            files3 = dir([PG3,filesep,'*.hdr']);
        end
        if isempty(files3)
            files3 = dir([PG3,filesep,'*.nii.gz']);
        end
        for i = 1:length(files3)
            IMGdirs{i,1} = [PG3,filesep,files3(i).name];
        end
        
        copydata2targetwithT1(PGout,ROIdirs,IMGdirs,T1dirs,namelist)
    end
end

close(ReGD.fig);
end

function SelEPIT1T2CT(Tempfile,i,opt,matdir,tab4end,Lab,dirs,namelist)

Con.config = figure('unit','norm',...
    'pos',[0.05,0.05,0.9,0.9]);
Con.maintext = uibuttongroup('parent',Con.config,...
    'unit','norm',...
    'pos',[0.05,0.05,0.9,0.9]);
Con.AllSel = uibuttongroup('parent',Con.config,...
    'unit','norm',...
    'pos',[0.05,0.95,0.9,0.05]);
Con.Nexbut = uicontrol('parent',Con.config,...
    'unit','norm',...
    'pos',[0.4,0,0.2,0.05],...
    'style','pushbutton',...
    'string',opt);

for j = 1:size(Tempfile,2)
    Con.Seltype(j,1) = uibuttongroup('parent',Con.AllSel,...
        'unit','norm',...
        'pos',[(j-1)/size(Tempfile,2),0,1/size(Tempfile,2),1]);
    Con.Seltypesel(j,1) = uicontrol('parent',Con.Seltype(j,1),...
        'unit','norm',...
        'pos',[0,2/3,1,1/3],...
        'style','rad',...
        'string','No sel');
    Con.Seltypesel(j,2) = uicontrol('parent',Con.Seltype(j,1),...
        'unit','norm',...
        'pos',[0,1/3,1,1/3],...
        'style','rad',...
        'string',Lab);
    Con.Seltypesel(j,3) = uicontrol('parent',Con.Seltype(j,1),...
        'unit','norm',...
        'pos',[0,0/3,1,1/3],...
        'style','rad',...
        'string','ROI');
end
for k = 1:size(Tempfile,1)
    for j = 1:size(Tempfile,2)
        Con.Show(j,k) = uibuttongroup('parent',Con.maintext,...
            'unit','norm',...
            'pos',[(j-1)/size(Tempfile,2),1-k/size(Tempfile,1),1/size(Tempfile,2),1/size(Tempfile,1)]);
        Con.ShowSelNo(j,k) = uicontrol('parent',Con.Show(j,k),...
            'unit','norm',...
            'pos',[0,0,1/3,0.5],...
            'style','rad',...
            'string','no');
        Con.ShowSelEPI(j,k) = uicontrol('parent',Con.Show(j,k),...
            'unit','norm',...
            'pos',[1/3,0,1/3,0.5],...
            'style','rad',...
            'string',Lab);
        Con.ShowSelROI(j,k) = uicontrol('parent',Con.Show(j,k),...
            'unit','norm',...
            'pos',[2/3,0,1/3,0.5],...
            'style','rad',...
            'string','ROI');
        Con.ShowDat(j,k) = uicontrol('parent',Con.Show(j,k),...
            'unit','norm',...
            'style','text',...
            'pos',[0,0.5,1,0.5],...
            'string',Tempfile(k,j));
    end
end
set(Con.Seltypesel,'callback',{@AllSel,Con});
set(Con.Nexbut,'callback',{@NextBut,Con,Tempfile,i,matdir,tab4end,dirs,namelist});
uiwait(Con.config)
end
function AllSel(varargin)
Con = varargin{3};
Nsize = size(Con.ShowSelNo,2);
% Val = get(Con.Seltypesel,'val');
for i = 1:size(Con.Seltypesel,1)
    val(i,1) = get(Con.Seltypesel(i,1),'val');
    val(i,2) = get(Con.Seltypesel(i,2),'val');
    val(i,3) = get(Con.Seltypesel(i,3),'val');
    if val(i,1)
        for j = 1:Nsize
            set(Con.ShowSelNo(i,j),'val',1);
            set(Con.ShowSelEPI(i,j),'val',0);
            set(Con.ShowSelROI(i,j),'val',0);
        end
    elseif val(i,2)        
        for j = 1:Nsize
            set(Con.ShowSelNo(i,j),'val',0);
            set(Con.ShowSelEPI(i,j),'val',1);
            set(Con.ShowSelROI(i,j),'val',0);
        end
    elseif val(i,3)        
        for j = 1:Nsize
            set(Con.ShowSelNo(i,j),'val',0);
            set(Con.ShowSelEPI(i,j),'val',0);
            set(Con.ShowSelROI(i,j),'val',1);
        end
    end
end
end
function NextBut(varargin)
Con = varargin{3};
Tempfile = varargin{4};
i = varargin{5};
matdir = varargin{6};
tab4end = varargin{7};
dirs = varargin{8};
namelist = varargin{9};

Nsize = size(Con.ShowSelNo,2);
Nimg = size(Con.ShowSelNo,1);
for j = 1:Nimg
    for k = 1:Nsize
        ValsImg(j,k) = get(Con.ShowSelEPI(j,k),'val');
        ValsROI(j,k) = get(Con.ShowSelROI(j,k),'val');
    end
end
indimg = find(ValsImg);
indROI = find(ValsROI);
[indimgx indimgy] = ind2sub([Nimg,Nsize],indimg);
[indROIx indROIy] = ind2sub([Nimg,Nsize],indROI);
for j = 1:length(indimgx)
    IMGdir{j,1} = [dirs{j},Tempfile{indimgy(j),indimgx(j)}];
end
for j = 1:length(indROIx)
    ROIdir{j,1} = [dirs{j},Tempfile{indROIy(j),indROIx(j)}];    
end
save([matdir,'ReGroupSetup',sprintf('%05d',i),'.mat'],'IMGdir','ROIdir');
if tab4end==1 % not the last
    PGout = uigetdir(pwd,'Where do you want to store the regroup data');
    mats = dir([matdir,'ReGroupSetup*.mat']);
    load([matdir,mats(1).name]);
    ROIdirs = ROIdir;
    IMGdirs = IMGdir;
    nsize = length(ROIdir);
    for j = 2:length(mats)
        load([matdir,mats(j).name]);
        NSIZE = length(ROIdir);
        ROIdirs(nsize+1:NSIZE+nsize) = ROIdir;
        IMGdirs(nsize+1:NSIZE+nsize) = IMGdir;
        nsize = nsize+NSIZE;
    end
%     save([PGout,filesep,'Rawfile.mat'],'ROIdirs','IMGdirs')
    copydata2target(PGout,ROIdirs,IMGdirs,namelist);
end
close(Con.config)
end

function SelWithT1(Tempfile,i,opt,matdir,tab4end,Lab,dirs,namelist)

Con.config = figure('unit','norm',...
    'pos',[0.05,0.05,0.9,0.9]);
Con.maintext = uibuttongroup('parent',Con.config,...
    'unit','norm',...
    'pos',[0.05,0.05,0.9,0.9]);
Con.AllSel = uibuttongroup('parent',Con.config,...
    'unit','norm',...
    'pos',[0.05,0.95,0.9,0.05]);
Con.Nexbut = uicontrol('parent',Con.config,...
    'unit','norm',...
    'pos',[0.4,0,0.2,0.05],...
    'style','pushbutton',...
    'string',opt);

for j = 1:size(Tempfile,2)
    Con.Seltype(j,1) = uibuttongroup('parent',Con.AllSel,...
        'unit','norm',...
        'pos',[(j-1)/size(Tempfile,2),0,1/size(Tempfile,2),1]);
    Con.Seltypesel(j,1) = uicontrol('parent',Con.Seltype(j,1),...
        'unit','norm',...
        'pos',[0,0.5,0.5,0.5],...
        'style','rad',...
        'string','No sel');
    Con.Seltypesel(j,2) = uicontrol('parent',Con.Seltype(j,1),...
        'unit','norm',...
        'pos',[0.5,0.5,0.5,0.5],...
        'style','rad',...
        'string','ROI');
    Con.Seltypesel(j,3) = uicontrol('parent',Con.Seltype(j,1),...
        'unit','norm',...
        'pos',[0,0,0.5,0.5],...
        'style','rad',...
        'string','Other');
    Con.Seltypesel(j,4) = uicontrol('parent',Con.Seltype(j,1),...
        'unit','norm',...
        'pos',[0.5,0,0.5,0.5],...
        'style','rad',...
        'string','T1');
end
for k = 1:size(Tempfile,1)
    for j = 1:size(Tempfile,2)
        Con.Show(j,k) = uibuttongroup('parent',Con.maintext,...
            'unit','norm',...
            'pos',[(j-1)/size(Tempfile,2),1-k/size(Tempfile,1),1/size(Tempfile,2),1/size(Tempfile,1)]);
        Con.ShowSelNo(j,k) = uicontrol('parent',Con.Show(j,k),...
            'unit','norm',...
            'pos',[0,0,1/4,0.5],...
            'style','rad',...
            'string','N');
        Con.ShowSelROI(j,k) = uicontrol('parent',Con.Show(j,k),...
            'unit','norm',...
            'pos',[1/4,0,1/4,0.5],...
            'style','rad',...
            'string','R');
        Con.ShowSelOther(j,k) = uicontrol('parent',Con.Show(j,k),...
            'unit','norm',...
            'pos',[2/4,0,1/4,0.5],...
            'style','rad',...
            'string','O');
        Con.ShowSelT1(j,k) = uicontrol('parent',Con.Show(j,k),...
            'unit','norm',...
            'pos',[3/4,0,1/4,0.5],...
            'style','rad',...
            'string','T');
        Con.ShowDat(j,k) = uicontrol('parent',Con.Show(j,k),...
            'unit','norm',...
            'style','text',...
            'pos',[0,0.5,1,0.5],...
            'string',Tempfile(k,j));
    end
end
set(Con.Seltypesel,'callback',{@AllSel2,Con});
set(Con.Nexbut,'callback',{@NextBut2,Con,Tempfile,i,matdir,tab4end,dirs,namelist});
uiwait(Con.config)
end
function AllSel2(varargin)
Con = varargin{3};
Nsize = size(Con.ShowSelNo,2);
% Val = get(Con.Seltypesel,'val');
for i = 1:size(Con.Seltypesel,1)
    val(i,1) = get(Con.Seltypesel(i,1),'val');
    val(i,2) = get(Con.Seltypesel(i,2),'val');
    val(i,3) = get(Con.Seltypesel(i,3),'val');
    val(i,4) = get(Con.Seltypesel(i,4),'val');
    if val(i,1)
        for j = 1:Nsize
            set(Con.ShowSelNo(i,j),'val',1);
            set(Con.ShowSelROI(i,j),'val',0);
            set(Con.ShowSelOther(i,j),'val',0);
            set(Con.ShowSelT1(i,j),'val',0);
        end
    elseif val(i,2)        
        for j = 1:Nsize
            set(Con.ShowSelNo(i,j),'val',0);
            set(Con.ShowSelROI(i,j),'val',1);
            set(Con.ShowSelOther(i,j),'val',0);
            set(Con.ShowSelT1(i,j),'val',0);
        end
    elseif val(i,3)        
        for j = 1:Nsize
            set(Con.ShowSelNo(i,j),'val',0);
            set(Con.ShowSelROI(i,j),'val',0);
            set(Con.ShowSelOther(i,j),'val',1);
            set(Con.ShowSelT1(i,j),'val',0);
        end
    elseif val(i,4)        
        for j = 1:Nsize
            set(Con.ShowSelNo(i,j),'val',0);
            set(Con.ShowSelROI(i,j),'val',0);
            set(Con.ShowSelOther(i,j),'val',0);
            set(Con.ShowSelT1(i,j),'val',1);
        end
    end
end
end
function NextBut2(varargin)
Con = varargin{3};
Tempfile = varargin{4};
i = varargin{5};
matdir = varargin{6};
tab4end = varargin{7};
dirs = varargin{8};
namelist = varargin{9};

Nsize = size(Con.ShowSelNo,2);
Nimg = size(Con.ShowSelNo,1);
for j = 1:Nimg
    for k = 1:Nsize
        ValsImg(j,k) = get(Con.ShowSelOther(j,k),'val');
        ValsROI(j,k) = get(Con.ShowSelROI(j,k),'val');
        ValsT1(j,k) = get(Con.ShowSelT1(j,k),'val');
    end
end
indimg = find(ValsImg);
indROI = find(ValsROI);
indT1 = find(ValsT1);
[indimgx indimgy] = ind2sub([Nimg,Nsize],indimg);
[indROIx indROIy] = ind2sub([Nimg,Nsize],indROI);
[indT1x indT1y] = ind2sub([Nimg,Nsize],indT1);
for j = 1:length(indimgx)
    IMGdir{j,1} = [dirs{j},Tempfile{indimgy(j),indimgx(j)}];
end
for j = 1:length(indROIx)
    ROIdir{j,1} = [dirs{j},Tempfile{indROIy(j),indROIx(j)}];    
end
for j = 1:length(indROIx)
    T1dir{j,1} = [dirs{j},Tempfile{indT1y(j),indT1x(j)}];    
end
save([matdir,'ReGroupSetup',sprintf('%05d',i),'.mat'],'IMGdir','ROIdir','T1dir');
if tab4end==1 % not the last
    PGout = uigetdir(pwd,'Where do you want to store the regroup data');
    mats = dir([matdir,'ReGroupSetup*.mat']);
    load([matdir,mats(1).name]);
    ROIdirs = ROIdir;
    IMGdirs = IMGdir;
    T1dirs = T1dir;
    nsize = length(ROIdir);
    for j = 2:length(mats)
        load([matdir,mats(j).name]);
        NSIZE = length(ROIdir);
        ROIdirs(nsize+1:NSIZE+nsize) = ROIdir;
        IMGdirs(nsize+1:NSIZE+nsize) = IMGdir;
        T1dirs(nsize+1:NSIZE+nsize) = T1dir;
        nsize = nsize+NSIZE;
    end
%     save([PGout,filesep,'Rawfile.mat'],'ROIdirs','IMGdirs')
    copydata2targetwithT1(PGout,ROIdirs,IMGdirs,T1dirs,namelist);
end
close(Con.config)
end

function SeltypeCond1(totalnum,DAT1,DAT2,DAT3,DAT4,files)

SelType.fig = figure('unit','norm',...
    'pos',[0.2,0.3,0.6,0.4]);
SelType.dat1 = uibuttongroup('parent',SelType.fig,...
    'unit','norm',...
    'pos',[0.1,0.25,0.4,0.75],...
    'title','Cond1');
SelType.dat2 = uibuttongroup('parent',SelType.fig,...
    'unit','norm',...
    'pos',[0.5,0.25,0.4,0.75],...
    'title','Cond2');

if totalnum/2<10
    exampshow1 = DAT1;
    exampshow2 = DAT2;
    exampshow3 = DAT3;
    exampshow4 = DAT4;
else
    exampshow1 = DAT1(1:10);
    exampshow2 = DAT2(1:10);
    exampshow3 = DAT3(1:10);
    exampshow4 = DAT4(1:10);
end
totnum = length(exampshow1);
for isize = 1:totnum
    SelType.dat1sel1 = uicontrol('parent',SelType.dat1,...
        'unit','norm',...
        'pos',[0,1-isize/totnum,0.5,1/totnum],...
        'style','text',...
        'string',exampshow1{isize});
    SelType.dat1sel2 = uicontrol('parent',SelType.dat1,...
        'unit','norm',...
        'pos',[0.5,1-isize/totnum,0.5,1/totnum],...
        'style','text',...
        'string',exampshow2{isize});
    SelType.dat2sel1 = uicontrol('parent',SelType.dat2,...
        'unit','norm',...
        'pos',[0,1-isize/totnum,0.5,1/totnum],...
        'style','text',...
        'string',exampshow3{isize});
    SelType.dat2sel2 = uicontrol('parent',SelType.dat2,...
        'unit','norm',...
        'pos',[0.5,1-isize/totnum,0.5,1/totnum],...
        'style','text',...
        'string',exampshow4{isize});
end
SelType.ROIs1 = uibuttongroup('parent',SelType.fig,...
    'unit','norm',...
    'pos',[0.1,0.05,0.8,0.1]);
SelType.ROIs2 = uibuttongroup('parent',SelType.fig,...
    'unit','norm',...
    'pos',[0.1,0.15,0.8,0.1]);
%%
SelType.roi(1) = uicontrol('parent',SelType.ROIs1,...
    'unit','norm',...
    'pos',[0,0,1/4,1],...
    'style','rad',...
    'string','ROI');
SelType.roi(2) = uicontrol('parent',SelType.ROIs1,...
    'unit','norm',...
    'pos',[1/4,0,1/4,1],...
    'style','rad',...
    'string','ROI');
SelType.roi(3) = uicontrol('parent',SelType.ROIs1,...
    'unit','norm',...
    'pos',[2/4,0,1/4,1],...
    'style','rad',...
    'string','ROI');
SelType.roi(4) = uicontrol('parent',SelType.ROIs1,...
    'unit','norm',...
    'pos',[3/4,0,1/4,1],...
    'style','rad',...
    'string','ROI');

SelType.T1(1) = uicontrol('parent',SelType.ROIs2,...
    'unit','norm',...
    'pos',[0,0,1/4,1],...
    'style','rad',...
    'string',Lab);
SelType.T1(2) = uicontrol('parent',SelType.ROIs2,...
    'unit','norm',...
    'pos',[1/4,0,1/4,1],...
    'style','rad',...
    'string',Lab);
SelType.T1(3) = uicontrol('parent',SelType.ROIs2,...
    'unit','norm',...
    'pos',[2/4,0,1/4,1],...
    'style','rad',...
    'string',Lab);
SelType.T1(4) = uicontrol('parent',SelType.ROIs2,...
    'unit','norm',...
    'pos',[3/4,0,1/4,1],...
    'style','rad',...
    'string',Lab);

SelType.Done = uicontrol('parent',SelType.fig,...
    'unit','norm',...
    'pos',[0.45,0,0.1,0.05],...
    'style','pushbutton',...
    'string','Done');
set(SetType.Done,'callback',{@DoneJob,SelType,DAT1,DAT2,DAT3,DAT4,files})

end
function DoneJob(varargin)
SelType = varargin{3};
% files = varargin{4};
DAT1 = varargin{4};
DAT2 = varargin{5};
DAT3 = varargin{6};
DAT4 = varargin{7};
files = varargin{8};
filenum = length(files);
PGout = uigetdir(pwd,'Outputdir');
for i = 1:4
    ROIval(i,1) = get(SelType.roi(i),'val');
    T1val(i,1) = get(SelType.T1(i),'val');
end
if ROIval(1) % first part to be ROI
    ROIlist = files(1:filenum/2);
elseif ROIval(2) % second part to be ROI
    ROIlist = files(1+filenum/2:filenum);    
elseif ROIval(3) % 1:2:end
    ROIlist = files(1:2:filenum);    
elseif ROIval(4) % 2:2:end
    ROIlist = files(2:2:filenum);
end
if T1val(1) % first part to be T1
    T1list = files(1:filenum/2);   
    namelist0 = DAT1;
elseif T1val(2) % second part to be T1
    T1list = files(1+filenum/2:filenum);   
    namelist0 = DAT2;  
elseif T1val(3) % 1:2:end
    T1list = files(1:2:filenum);   
    namelist0 = DAT3;     
elseif T1val(4) % 2:2:end
    T1list = files(2:2:filenum);
    namelist0 = DAT4;
end
for i = 1:length(namelist0)
    tempname = namelist0{i};
    dotcond = find(tempname=='.');
    namelist{i,1} = tempname(1:dotcond(1)-1);
end
copydata2target(PGout,ROIlist,T1list,namelist)
end

function SeltypeCond2(totalnum,DAT1,DAT2,DAT3,DAT4,DAT5,DAT6,files)

SelType.fig = figure('unit','norm',...
    'pos',[0.2,0.3,0.6,0.4]);
SelType.dat1 = uibuttongroup('parent',SelType.fig,...
    'unit','norm',...
    'pos',[0.1,0.25,0.4,0.75],...
    'title','Cond1');
SelType.dat2 = uibuttongroup('parent',SelType.fig,...
    'unit','norm',...
    'pos',[0.5,0.25,0.4,0.75],...
    'title','Cond2');

if totalnum/3<10
    exampshow1 = DAT1;
    exampshow2 = DAT2;
    exampshow3 = DAT3;
    exampshow4 = DAT4;
    exampshow5 = DAT5;
    exampshow6 = DAT6;
else
    exampshow1 = DAT1(1:10);
    exampshow2 = DAT2(1:10);
    exampshow3 = DAT3(1:10);
    exampshow4 = DAT4(1:10);
    exampshow5 = DAT5(1:10);
    exampshow6 = DAT6(1:10);
end
totnum = length(exampshow1);
for isize = 1:totnum
    SelType.dat1sel1 = uicontrol('parent',SelType.dat1,...
        'unit','norm',...
        'pos',[0,1-isize/totnum,1/3,1/totnum],...
        'style','text',...
        'string',exampshow1{isize});
    SelType.dat1sel2 = uicontrol('parent',SelType.dat1,...
        'unit','norm',...
        'pos',[1/3,1-isize/totnum,1/3,1/totnum],...
        'style','text',...
        'string',exampshow2{isize});
    SelType.dat1sel3 = uicontrol('parent',SelType.dat1,...
        'unit','norm',...
        'pos',[2/3,1-isize/totnum,1/3,1/totnum],...
        'style','text',...
        'string',exampshow3{isize});
    
    SelType.dat2sel1 = uicontrol('parent',SelType.dat2,...
        'unit','norm',...
        'pos',[0,1-isize/totnum,1/3,1/totnum],...
        'style','text',...
        'string',exampshow4{isize});
    SelType.dat2sel2 = uicontrol('parent',SelType.dat2,...
        'unit','norm',...
        'pos',[1/3,1-isize/totnum,1/3,1/totnum],...
        'style','text',...
        'string',exampshow5{isize});
    SelType.dat2sel3 = uicontrol('parent',SelType.dat2,...
        'unit','norm',...
        'pos',[2/3,1-isize/totnum,1/3,1/totnum],...
        'style','text',...
        'string',exampshow6{isize});
end
SelType.ROIs1 = uibuttongroup('parent',SelType.fig,...
    'unit','norm',...
    'pos',[0.1,0.05,0.8,0.2/3]);
SelType.ROIs2 = uibuttongroup('parent',SelType.fig,...
    'unit','norm',...
    'pos',[0.1,0.05+0.2/3,0.8,0.2/3]);
SelType.ROIs3 = uibuttongroup('parent',SelType.fig,...
    'unit','norm',...
    'pos',[0.1,0.05+0.4/3,0.8,0.2/3]);
%%
SelType.roi(1) = uicontrol('parent',SelType.ROIs1,...
    'unit','norm',...
    'pos',[0,0,1/6,1],...
    'style','rad',...
    'string','ROI');
SelType.roi(2) = uicontrol('parent',SelType.ROIs1,...
    'unit','norm',...
    'pos',[1/6,0,1/6,1],...
    'style','rad',...
    'string','ROI');
SelType.roi(3) = uicontrol('parent',SelType.ROIs1,...
    'unit','norm',...
    'pos',[2/6,0,1/6,1],...
    'style','rad',...
    'string','ROI');
SelType.roi(4) = uicontrol('parent',SelType.ROIs1,...
    'unit','norm',...
    'pos',[3/6,0,1/6,1],...
    'style','rad',...
    'string','ROI');
SelType.roi(5) = uicontrol('parent',SelType.ROIs1,...
    'unit','norm',...
    'pos',[4/6,0,1/6,1],...
    'style','rad',...
    'string','ROI');
SelType.roi(6) = uicontrol('parent',SelType.ROIs1,...
    'unit','norm',...
    'pos',[5/6,0,1/6,1],...
    'style','rad',...
    'string','ROI');

SelType.Other(1) = uicontrol('parent',SelType.ROIs2,...
    'unit','norm',...
    'pos',[0,0,1/6,1],...
    'style','rad',...
    'string',Lab);
SelType.Other(2) = uicontrol('parent',SelType.ROIs2,...
    'unit','norm',...
    'pos',[1/6,0,1/6,1],...
    'style','rad',...
    'string',Lab);
SelType.Other(3) = uicontrol('parent',SelType.ROIs2,...
    'unit','norm',...
    'pos',[2/6,0,1/6,1],...
    'style','rad',...
    'string',Lab);
SelType.Other(4) = uicontrol('parent',SelType.ROIs2,...
    'unit','norm',...
    'pos',[3/6,0,1/6,1],...
    'style','rad',...
    'string',Lab);
SelType.Other(5) = uicontrol('parent',SelType.ROIs2,...
    'unit','norm',...
    'pos',[4/6,0,1/6,1],...
    'style','rad',...
    'string',Lab);
SelType.Other(6) = uicontrol('parent',SelType.ROIs2,...
    'unit','norm',...
    'pos',[5/6,0,1/6,1],...
    'style','rad',...
    'string',Lab);

SelType.T1(1) = uicontrol('parent',SelType.ROIs3,...
    'unit','norm',...
    'pos',[0,0,1/6,1],...
    'style','rad',...
    'string','T1');
SelType.T1(2) = uicontrol('parent',SelType.ROIs3,...
    'unit','norm',...
    'pos',[1/6,0,1/6,1],...
    'style','rad',...
    'string','T1');
SelType.T1(3) = uicontrol('parent',SelType.ROIs3,...
    'unit','norm',...
    'pos',[2/6,0,1/6,1],...
    'style','rad',...
    'string','T1');
SelType.T1(4) = uicontrol('parent',SelType.ROIs3,...
    'unit','norm',...
    'pos',[3/6,0,1/6,1],...
    'style','rad',...
    'string','T1');
SelType.T1(5) = uicontrol('parent',SelType.ROIs3,...
    'unit','norm',...
    'pos',[4/6,0,1/6,1],...
    'style','rad',...
    'string','T1');
SelType.T1(6) = uicontrol('parent',SelType.ROIs3,...
    'unit','norm',...
    'pos',[5/6,0,1/6,1],...
    'style','rad',...
    'string','T1');

SelType.Done = uicontrol('parent',SelType.fig,...
    'unit','norm',...
    'pos',[0.45,0,0.1,0.05],...
    'style','pushbutton',...
    'string','Done');
set(SetType.Done,'callback',{@DoneJob2,SelType,DAT1,DAT2,DAT3,DAT4,DAT5,DAT6,files})
% set(SetType.Done,'callback',{@DoneJob,SelType,files})
end
function DoneJob2(varargin)
SelType = varargin{3};
% files = varargin{4};
DAT1 = varargin{4};
DAT2 = varargin{5};
DAT3 = varargin{6};
DAT4 = varargin{7};
DAT5 = varargin{8};
DAT6 = varargin{9};
files = varargin{10};
filenum = length(files);
PGout = uigetdir(pwd,'Outputdir');
for i = 1:4
    ROIval(i,1) = get(SelType.roi(i),'val');
    Otherval(i,1) = get(SelType.Other(i),'val');
    T1val(i,1) = get(SelType.T1(i),'val');
end
if ROIval(1) % first part to be ROI
    ROIlist = files(1:filenum/3);
elseif ROIval(2) % second part to be ROI
    ROIlist = files(1+filenum/3:filenum/3*2);    
elseif ROIval(3) % 1:2:end
    ROIlist = files(1+filenum/3*2:filenum);    
elseif ROIval(4) % 2:2:end
    ROIlist = files(1:3:filenum);
elseif ROIval(5) % 2:2:end
    ROIlist = files(2:3:filenum);
elseif ROIval(6) % 2:2:end
    ROIlist = files(3:3:filenum);
end

if Otherval(1) % first part to be ROI
    Otherlist = files(1:filenum/3);
elseif Otherval(2) % second part to be ROI
    Otherlist = files(1+filenum/3:filenum/3*2);    
elseif Otherval(3) % 1:2:end
    Otherlist = files(1+filenum/3*2:filenum);    
elseif Otherval(4) % 2:2:end
    Otherlist = files(1:3:filenum);
elseif Otherval(5) % 2:2:end
    Otherlist = files(2:3:filenum);
elseif Otherval(6) % 2:2:end
    Otherlist = files(3:3:filenum);
end

if T1val(1) % first part to be T1
    T1list = files(1:filenum/3);   
    namelist0 = DAT1;
elseif T1val(2) % second part to be T1
    T1list = files(1+filenum/3:filenum/3*2);   
    namelist0 = DAT2;  
elseif T1val(3) % 1:2:end
    T1list = files(1+filenum/3*2:filenum);   
    namelist0 = DAT3;     
elseif T1val(4) % 2:2:end
    T1list = files(1:3:filenum);
    namelist0 = DAT4;
elseif T1val(5) % 2:2:end
    T1list = files(2:3:filenum);
    namelist0 = DAT5;
elseif T1val(6) % 2:2:end
    T1list = files(3:3:filenum);
    namelist0 = DAT6;
end

for i = 1:length(namelist0)
    tempname = namelist0{i};
    dotcond = find(tempname=='.');
    namelist{i,1} = tempname(1:dotcond(1)-1);
end
% copydata2targetwithT1(PGout,ROIdirs,IMGdirs,T1dirs,namelist)
copydata2targetwithT1(PGout,ROIlist,Otherlist,T1list,namelist)
end

